export const NameSpace = {
  CARDS: `CARDS`,
  USER: `USER`,
  CITY_SELECT: `CITY_SELECT`,
  CARD_SELECT: `CARD_SELECT`,
  CARDS_SORTING_MENU: `CARDS_SORTING_MENU`,
  REVIEWS: `REVIEWS`,
  SIMILAR_OFFERS: `SIMILAR_OFFERS`,
};
